server:
  port: 8077
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    # driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:log4jdbc:mariadb://127.0.0.1:3306/wikenDevelopment?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: sbsst
    password: sbs123414
mybatis:
  type-aliases-package: com.jhs.wiken.vo
custom:
  logging:
    dir: log
    level: debug